# Generated by Django 4.1.6 on 2023-03-06 18:57

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0002_delete_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Driver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=15)),
                ('destination', models.CharField(max_length=15)),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('phone', models.CharField(max_length=12)),
                ('name', models.CharField(max_length=25)),
                ('userId', models.IntegerField()),
                ('Seats', models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)])),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.IntegerField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(5)])),
                ('comment', models.CharField(max_length=255)),
                ('driver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.driver')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='accounts.passenger')),
            ],
        ),
        migrations.AddField(
            model_name='passenger',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_destination', to='accounts.ride'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='ride_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_date', to='accounts.ride'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='ride_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_time', to='accounts.ride'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='passenger_source', to='accounts.ride'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='driver',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_destination', to='accounts.ride'),
        ),
        migrations.AddField(
            model_name='driver',
            name='ride_date',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_date', to='accounts.ride'),
        ),
        migrations.AddField(
            model_name='driver',
            name='ride_time',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_time', to='accounts.ride'),
        ),
        migrations.AddField(
            model_name='driver',
            name='source',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='driver_source', to='accounts.ride'),
        ),
        migrations.AddField(
            model_name='driver',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
