# Generated by Django 4.1.6 on 2023-03-07 18:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='passenger',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='ride_date',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='ride_time',
        ),
        migrations.RemoveField(
            model_name='passenger',
            name='source',
        ),
        migrations.AddField(
            model_name='passenger',
            name='ride',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='accounts.ride'),
        ),
        migrations.AddField(
            model_name='ride',
            name='visible',
            field=models.BooleanField(default=True),
        ),
    ]
