# Generated by Django 4.1.6 on 2023-03-07 18:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_ride_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='Seats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
