# Generated by Django 4.1.6 on 2023-03-07 18:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_ride_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passenger',
            name='ride',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ride'),
        ),
    ]
