# Generated by Django 4.0.4 on 2023-03-10 16:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0010_alter_review_driver_alter_review_reviewer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='userId',
        ),
        migrations.AddField(
            model_name='ride',
            name='driver',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
