# Generated by Django 4.0.4 on 2023-03-10 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_ride_userid_ride_driver'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='Seats',
            new_name='seats',
        ),
        migrations.RemoveField(
            model_name='ride',
            name='name',
        ),
    ]
