# Generated by Django 4.0.4 on 2023-02-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ride',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.TextField()),
                ('destination', models.TextField()),
                ('date', models.DateField()),
                ('time', models.TimeField()),
                ('phone', models.TextField()),
                ('name', models.TextField()),
            ],
        ),
    ]
