# Generated by Django 4.0.4 on 2023-02-10 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridelist', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='destination',
            field=models.CharField(choices=[('halifax', 'HALIFAX'), ('sydney', 'SYDNEY'), ('antigonish', 'ANTIGONISH'), ('moncton', 'MONCTON'), ('truro', 'TRURO')], max_length=15),
        ),
        migrations.AlterField(
            model_name='ride',
            name='source',
            field=models.CharField(choices=[('halifax', 'HALIFAX'), ('sydney', 'SYDNEY'), ('antigonish', 'ANTIGONISH'), ('moncton', 'MONCTON'), ('truro', 'TRURO')], max_length=15),
        ),
    ]
