# Generated by Django 4.0.4 on 2023-02-10 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridelist', '0002_alter_ride_destination_alter_ride_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ride',
            name='name',
            field=models.CharField(max_length=25),
        ),
        migrations.AlterField(
            model_name='ride',
            name='phone',
            field=models.CharField(max_length=12),
        ),
    ]
