# Generated by Django 4.0.4 on 2023-02-23 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ridelist', '0007_alter_ride_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='userId',
            new_name='user',
        ),
    ]
