# Generated by Django 4.0.4 on 2023-02-23 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridelist', '0008_rename_userid_ride_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ride',
            name='user',
        ),
        migrations.AddField(
            model_name='ride',
            name='userId',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
