# Generated by Django 4.1.6 on 2023-03-06 17:03

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ridelist', '0009_remove_ride_user_ride_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ride',
            name='seats',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(4)]),
        ),
    ]
