# Generated by Django 4.1.6 on 2023-03-06 17:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ridelist', '0010_ride_seats'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ride',
            old_name='seats',
            new_name='Seats',
        ),
    ]
